/**
 * @file mpconfigboard.h
 * @brief 小喵掌机 MicroPython 板级配置
 */

#ifndef MICROPY_INCLUDED_BOARD_MPCONFIGBOARD_H
#define MICROPY_INCLUDED_BOARD_MPCONFIGBOARD_H

// 启用必要的模块
#define MICROPY_PY_BUILTINS_STR_UNICODE (1)
#define MICROPY_PY_BUILTINS_BYTEARRAY (1)
#define MICROPY_PY_BUILTINS_MEMORYVIEW (1)
#define MICROPY_PY_BUILTINS_SLICE_ATTRS (1)
#define MICROPY_PY_ALL_SPECIAL_METHODS (1)
#define MICROPY_PY_REVERSE_SPECIAL_METHODS (1)
#define MICROPY_PY_ARRAY_SLICE_ASSIGN (1)
#define MICROPY_PY_COLLECTIONS_DEQUE (1)
#define MICROPY_PY_COLLECTIONS_ORDEREDDICT (1)
#define MICROPY_PY_MATH_SPECIAL_FUNCTIONS (1)
#define MICROPY_PY_MATH_FACTORIAL (1)
#define MICROPY_PY_CMATH (1)
#define MICROPY_PY_IO_IOBASE (1)
#define MICROPY_PY_STRUCT (1)
#define MICROPY_PY_UHEAPQ (1)
#define MICROPY_PY_UTIMEQ (1)

// 禁用不必要的模块以节省空间
#define MICROPY_PY_USSL (0)
#define MICROPY_PY_BTREE (0)
#define MICROPY_PY_MACHINE_I2C (0)
#define MICROPY_PY_MACHINE_SPI (0)
#define MICROPY_PY_MACHINE_UART (0)
#define MICROPY_PY_MACHINE_ADC (0)
#define MICROPY_PY_MACHINE_DAC (0)
#define MICROPY_PY_MACHINE_PWM (0)
#define MICROPY_PY_MACHINE_PIN (0)
#define MICROPY_PY_MACHINE_RTC (0)
#define MICROPY_PY_MACHINE_TIMER (0)
#define MICROPY_PY_MACHINE_WDT (0)

// FATFS 支持（禁用 MicroPython 自带的 fatfs，使用 ESP-IDF 自带的 fatfs 避免链接冲突）
#define MICROPY_VFS_FAT (0)
#define MICROPY_VFS_LFS2 (0)

// 内存配置
#define MICROPY_GC_STACK_ENTRY_TYPE uint16_t
#define MICROPY_ENABLE_GC (1)
#define MICROPY_ENABLE_FINALISER (1)
#define MICROPY_STACK_CHECK (1)
#define MICROPY_KBD_EXCEPTION (1)
#define MICROPY_HELPER_REPL (1)
#define MICROPY_REPL_EMACS_KEYS (1)
#define MICROPY_REPL_AUTO_INDENT (1)
#define MICROPY_REPL_EVENT_DRIVEN (0)

// 异常处理
#define MICROPY_CPYTHON_COMPAT (1)
#define MICROPY_FULL_CHECKS (1)
#define MICROPY_STREAMS_POSIX_API (1)

// 浮点数支持
#define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_DOUBLE)

#endif // MICROPY_INCLUDED_BOARD_MPCONFIGBOARD_H